apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberniq-chat-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/oluwaTG/kuberniq'
    targetRevision: main
    path: ./helm/Application/kuberniq-chat
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kuberniq-chat-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
